# Generated by Django 4.1.5 on 2023-01-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='have_header',
            field=models.BooleanField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='home',
            name='have_picture',
            field=models.BooleanField(null=True, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='home',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='index/static/index/img'),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
