# Generated by Django 4.1.5 on 2023-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_home_image_remove_home_title_home_have_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='right_pic',
            field=models.BooleanField(null=True, verbose_name='Картинка спарва в тексте?'),
        ),
        migrations.AlterField(
            model_name='home',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='HomePage/static/HomePage/img'),
        ),
    ]
