# Generated by Django 4.1.5 on 2023-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_home_right_pic_alter_home_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_picture', models.BooleanField(null=True, verbose_name='Изображение')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='HomePage/static/HomePage/img')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
    ]
