# Generated by Django 4.1.5 on 2023-01-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
