# Generated by Django 4.1.4 on 2023-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='demand', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('graph_left', models.ImageField(default=None, upload_to='demand', verbose_name='График №2')),
                ('graph_right', models.ImageField(default=None, upload_to='demand', verbose_name='График №1')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph',
            field=models.ImageField(default=None, upload_to='geography', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default=None, upload_to='home', verbose_name='img'),
        ),
    ]
