# Generated by Django 4.1.5 on 2023-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoVacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('have_picture', models.BooleanField(null=True, verbose_name='Изображение')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='HomePage/static/HomePage/img')),
                ('right_pic', models.BooleanField(null=True, verbose_name='Картинка спарва в тексте?')),
                ('have_header', models.BooleanField(null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
