# Generated by Django 4.1.5 on 2023-01-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoVacancy', '0002_home_delete_demand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Demand',
        ),
    ]
