# Generated by Django 4.1.5 on 2023-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='InfoVacancy/static/img')),
            ],
            options={
                'verbose_name': 'Графики вакансии за определённый год по городам',
                'verbose_name_plural': 'Графики',
            },
        ),
        migrations.CreateModel(
            name='Procent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(null=True, verbose_name='Город')),
                ('procent', models.FloatField(default=0, verbose_name='Доля от всех городов')),
            ],
            options={
                'verbose_name': 'Таблица долей вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по годам',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(null=True, verbose_name='Город')),
                ('salary', models.IntegerField(default=0, verbose_name='Доля от всех городов')),
            ],
            options={
                'verbose_name': 'Таблица уровня зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по годам',
            },
        ),
    ]
