# Generated by Django 4.1.5 on 2023-01-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procent',
            name='procent',
            field=models.IntegerField(default=0, verbose_name='Доля от всех городов'),
        ),
    ]
