# Generated by Django 4.1.5 on 2023-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geography', '0002_alter_procent_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procent',
            name='city',
            field=models.TextField(max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='city',
            field=models.TextField(max_length=20, null=True, verbose_name='Город'),
        ),
    ]
