# Generated by Django 4.1.5 on 2023-01-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Год')),
                ('first_skill', models.TextField(default=0, verbose_name='1 скилл')),
                ('second_skill', models.TextField(default=0, verbose_name='2 скилл')),
                ('third_skill', models.TextField(default=0, verbose_name='3 скилл')),
                ('forth_skill', models.TextField(default=0, verbose_name='4 скилл')),
                ('fifth_skill', models.TextField(default=0, verbose_name='5 скилл')),
                ('sixth_skill', models.TextField(default=0, verbose_name='6 скилл')),
                ('seventh_skill', models.TextField(default=0, verbose_name='7 скилл')),
                ('eighth_skill', models.TextField(default=0, verbose_name='8 скилл')),
                ('ninth_skill', models.TextField(default=0, verbose_name='9 скилл')),
                ('tenth_skill', models.TextField(default=0, verbose_name='10 скилл')),
            ],
            options={
                'verbose_name': 'Топ скиллов за определённый год',
                'verbose_name_plural': 'Скиллы',
            },
        ),
        migrations.CreateModel(
            name='SkillsGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Skills/static/img')),
            ],
            options={
                'verbose_name': 'Графики скиллов за определённый год',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
